services:

# Development service
  app-dev:
    container_name: react-app-dev
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      VITE_API_URL: http://localhost:3001
      NODENV: production
      PORT: 3000
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules